export * from "./About";
export * from "./ActionComp";
export * from "./AddEditEntity";
export * from "./ButtonX";
export * from "./Cal";
export * from "./Comp5";
export * from "./Header";
export * from "./Home";
// export * from "./ListEntities";
// export * from "./RenderList";
export * from "./NavigationBar";
export * from "./RandomPic";
