# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup-macos:
    name: Setup - MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Yarn Install
        run: yarn install
  e2e:
    name: Test - E2E
    runs-on: macos-latest
    needs: setup-macos
    env:
      CODE_SIGNING_REQUIRED: NO
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          brew tap wix/brew
          brew install --HEAD applesimutils
          npm install -g detox-cli
          npm install -g react-native-cli
          npm install
          react-native start --port 2137 &
          detox build -c ios.sim.debug 
          detox test -c ios.sim.debug
          kill -9 $(lsof -n -i4TCP:2137) 

  # detox_test:android:
  #   stage: test
  #   services:
  #   -   name: android-emulator:latest
  #       alias: pixel
  #       entrypoint: ["/start-emulator.sh", "android-23", "x86", "pixel"]
  #   before_script:
  #     - adb connect pixel:5555; sh ./scripts/waitForDevice.sh pixel 
  #     - mkdir -p ./detox_node/
  #     - npm install --prefix ./detox_node/ -g detox-cli
  #     - npm install --prefix ./detox_node/ -g react-native-cli
  #     - npm install
  #   script:
  #     - ./detox_node/bin/react-native start --port 2137 &
  #     - ./detox_node/bin/detox build -c android.emu.debug
  #     - ./detox_node/bin/detox test -c android.emu.debug
  #     - kill -9 $(lsof -n -i4TCP:2137) 
  #   tags:
  #     - android-emu
