# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  e2e:iOS:
      needs: build
      steps:
        - name: setup simulator
          run: brew tap wix/brew && brew install --HEAD applesimutils
        - name: setup detox-cli
          run: npm install -g detox-cli
        - name: setup react-native
          run: npm install -g react-native-cli
        - name: setup dependencies
          run: npm install
        - name: setup app in start mode
          run: react-native start --port 2137 &
        - name: detox build for e2e tests
          run: detox build -c ios.sim.debug 
        - name: detox e2e tests
          run: detox test -c ios.sim.debug
        - name: detox cleanup
          run: kill -9 $(lsof -n -i4TCP:2137) 

  # detox_test:android:
  #   stage: test
  #   services:
  #   -   name: android-emulator:latest
  #       alias: pixel
  #       entrypoint: ["/start-emulator.sh", "android-23", "x86", "pixel"]
  #   before_script:
  #     - adb connect pixel:5555; sh ./scripts/waitForDevice.sh pixel 
  #     - mkdir -p ./detox_node/
  #     - npm install --prefix ./detox_node/ -g detox-cli
  #     - npm install --prefix ./detox_node/ -g react-native-cli
  #     - npm install
  #   script:
  #     - ./detox_node/bin/react-native start --port 2137 &
  #     - ./detox_node/bin/detox build -c android.emu.debug
  #     - ./detox_node/bin/detox test -c android.emu.debug
  #     - kill -9 $(lsof -n -i4TCP:2137) 
  #   tags:
  #     - android-emu
