name: Cypress Tests
on: 
  push:
    branches:
      - "e2e-testing"
      - "develop"
jobs:
  cypress-run:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node: [14]
      steps:
        - uses: actions/checkout@v1
        - name: Cloning Rn Config Tyler
          run: | 
            cd src && git clone -b e2e-testing https://github.com/applerdotxyz/rn-config-tyler.git
        - name: RN Config Tyler Setup
          run: |
            cd src/rn-config-tyler && ls && yarn install
        - name: Setup Node
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node }}
        - uses: actions/cache@v1
          id: cache
          with:
            path: |
              ~/.cache/Cypress
              node_modules
            key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}  
        - name: Yarn Install
          run: |
            yarn install
            ls
        - name: expo global setup
          run: |
            npm install -g expo-cli
            ls
        - name: E2E testing
          uses: cypress-io/github-action@v2  
          with:
            build: yarn build:demo
            start: yarn serve:web



        
        
