name: main

on:
  push:
    branches:
      - code_quality
      - master
  pull_request:
    branches: [master]
jobs:
  setup-linux:
    name: Setup - Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14.13.1"
      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Yarn Install
        if: steps.cache.outputs.cache-hit != 'true' || steps.submodule-cache.outputs.cache-hit != 'true'
        run: yarn install
#       - name: install cypress globally
#         run: npm i -g cypress
#       - name: install cypress runner
#         run: cypress install
  test-lint:
    name: Test - Lint
    runs-on: ubuntu-latest
    needs: setup-linux
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14.13.1"
      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - uses: actions/cache@v2
        id: cache-cy
        with:
          path: /home/runner/.cache/Cypress/6.1.0
          key: cypress
      - name: Yarn Install
        if: steps.cache.outputs.cache-hit != 'true' || steps.submodule-cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Lint Report
        run: yarn lint-report
      - name: Test with coverage
        run: yarn coverage
      - name: E2E tests for web
        run: npx cypress run --record false
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  cypress-run:
    needs: setup-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
