


name: Cypress Tests
on: 
  push:
    branches:
      - "e2e-testing"
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
        id: cache
          with:
            path: |
              ~/.cache/Cypress
              node_modules
            key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }} 
      - name: Yarn Install
        run: yarn install
      - name: expo global setup
        run: npm install -g expo-cli
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build:demo
          start: yarn demo

